[package]
name = "unsignedbyte"
version = "0.1.0"
authors = ["UnsignedByte <edlam1889@gmail.com>"]
edition = "2018"

[lib]
name = "mylib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
